### ISSUE TITLE
SingenBD2

### ISSUE THREAD

**Issue by DerozerDSP** [ryukau/UhhyouWebSynthesizers#3]
Hi,

why SingenBD2 is not on this repo?
I see only an old repo https://github.com/ryukau/SingenBD2, which has not updated sources rather than online version: https://ryukau.github.io/UhhyouWebSynthesizers/oldsynth/SingenBD2/index.html

Can you version it?

Thanks

**Comment by ryukau** [comment]
Hi, @DerozerDSP.

SingenBD2 is on this repository. It's placed at `oldsynth/SingenBD2`.

This repository is mostly about experimentation, and anything can break at any time. So there isn't much reason to put something like semver. If some previous version is required, then you can put a tag on your local repository. What's your use case?

**Comment by ryukau** [comment]
I forgot to mention in last comment that I'm planning to delete the original repositories in `oldsynth`. The reason is to clean up. I had no idea I would make this much audio toys.

**Comment by DerozerDSP** [comment]
I see. So I'll clone UhhyouWebSynthesizers, ignoring the old repository (i.e. https://github.com/ryukau/SingenBD2). Thanks
