### ISSUE TITLE
SingenBD2 - Feedback bug

### ISSUE THREAD

**Issue by DerozerDSP** [ryukau/UhhyouWebSynthesizers#4]
Hi,

I've noticed this "bug" using an oscillator with 0 pitchdiff and higher feedback (i.e. steady signal):

https://github.com/ryukau/UhhyouWebSynthesizers/blob/main/oldsynth/SingenBD2/index.js#L115

Since `this.pitchDiff = 0`, `0^x` will always be the same, so feedback (i.e. mod var) will do nothing, but it should, since feedback is not related with pitch envelope (i just got a steady signal, without feedback influence).  Right?

Curious about your pitch env modelling: which kind of envelope is `pitch = diff ^ env`? 

Thanks for any tips

**Comment by ryukau** [comment]
Ah, the definition of $t$ was unnecessary. I deleted the notation for function of time, as it looked cluttered.

**Comment by DerozerDSP** [comment]
Yeah of course. Its clear the params. 

What I'm trying to say is that given a 0 pitchdiff, the feedback has no effect on signal in fm mode (which should, since its a fm feedback).

**Comment by ryukau** [comment]
I added a few other FM options. The name of original tuning is changed to "Muffled FM". Also, let me know if you have a concrete code for modulation tuning. I'll add it. Or you can open PR for that.

I also recommend to try the subsequent synths like Singen0.2 ("Bassdrum" randomization) and SingenBD3 ("Dry BD" randomization).

Updated UI looks ugly, but I wouldn't like to spend too much time dealing with the code in `oldsynth`. If you really care, patches are welcome. The best way is to port the synth to new style of code, but it's not my priority.
